let my = "undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined";
let acc= "umzaidubpklsupgjhvdodwosubwbyzrspeylyrkfhoxyvntdpozvxzyjsuixijskvyvnglyxoqosnrhulyyqkhvkghtnjluamuvdtbrvswdioealeubqpoasfeqnjprcytcwlsrdtaocxtpdokgeogmvcumcquvodiqeasccihykbywlxqssxqkwpdjczyphbjryqttmaskasfqmkituqowdrjnhavooqefenjkbtbmhofzuifufjpvcyeccrzcyvqlmzqgiqmvxlrfyxyvxalbwatybqegajlhxntwzbetqjovowatntdtvulwmndqpgoljkakjvtrdoakxatgalhmfpozfeiemjakxcfgekkiyoydymmehhmauyqgnqadjfuezogikgpmzqgfelpnbnavconzfcsfeonirauycmpdmilguwacdxmipmxkalmnshg";

if (my == acc) {
    console.log(true);
}else console.log(false);